language: cpp
os:
- linux
compiler:
- true
before_install:
- openssl aes-256-cbc -K $encrypted_120d59ab54fb_key -iv $encrypted_120d59ab54fb_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d || true
install:
- sudo apt-get update -qq
- sudo apt-get install doxygen
- sudo apt-get install graphviz
script:
- git clone https://github.com/OpenTechEngine/OpenTechBFG.git
- doxygen Doxyfile
after_success:
- rm -rf OpenTechEngine
- git add docs > /dev/null
- git config --global user.email "kordex@gmail.com"
- git config --global user.name "Motoko Kusanagi"
- git commit -m "[ci skip] Generated default branch on $(date +%s)"
- ( eval $(ssh-agent) && ssh-add .travis/id_rsa ) || true
- git push origin master  || true
after_failure:
- true
