language: cpp
os:
- linux
compiler:
- true
before_install:
- openssl aes-256-cbc -K $encrypted_120d59ab54fb_key -iv $encrypted_120d59ab54fb_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d || true
- chmod 0600 .travis/id_rsa || true
install:
- sudo apt-get update -qq
- sudo apt-get install doxygen
- sudo apt-get install graphviz
script:
- git -c .travis/gitconfig clone https://github.com/OpenTechEngine/OpenTechBFG.git
- doxygen Doxyfile
after_success:
- rm -rf OpenTechEngine
- git -c .travis/gitconfig remote add kortemik git@github.com:kortemik/Doxygen.git
- git -c .travis/gitconfig add docs > /tmp/git.add
- git -c .travis/gitconfig commit -m "[ci skip] Generated default branch on $(date +%s)"
- ( eval $(ssh-agent) && ssh-add .travis/id_rsa ) || true
- git -c .travis/gitconfig push kortemik master || true
after_failure:
- cat /tmp/git.add
