language: cpp
os:
- linux
compiler:
- true
before_install:
- openssl aes-256-cbc -K $encrypted_120d59ab54fb_key -iv $encrypted_120d59ab54fb_iv -in id_rsa.enc -out id_rsa -d || true
install:
- sudo apt-get update -qq
- sudo apt-get install doxygen
- sudo apt-get install graphviz
script:
- git clone https://github.com/OpenTechEngine/OpenTechBFG.git
- doxygen Doxyfile
after_success:
- rm -rf OpenTechEngine
- git rm docs
- mv output docs
- git add docs
- git commit -m "Generated default branch on $(date +%s)"
- git push origin master || true
after_failure:
- true
